version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-184-73-153-64.compute-1.amazonaws.com
            port: '5432'
            database: datpo9d93gjgva
            schema: public
            user: hwfqyaptxwydip
            password: fa6ddf823060bfc1e10bc327c7ddf7a3dbdba64cf95386aa79550c2953351dd3
            rawAccess: true
            migrations: true
            ssl: true